language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.3
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer selfupdate
  - composer install --prefer-dist --no-dev

script:
  - vendor/bin/tester tests -p php -s -c tests/php.ini

notifications:
  email: false