language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - mysql
  - postgresql

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database testbench_initial;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database testbench_initial;' -U postgres; fi"
  - composer selfupdate --no-progress
  - travis_retry composer install --prefer-dist --dev
  - mkdir tests/_temp
  - "sh -c \"if [ '$DB' = 'mysql' ]; then cp tests/_helpers/mysql.neon tests/tests.local.neon; fi\""
  - "sh -c \"if [ '$DB' = 'pgsql' ]; then cp tests/_helpers/pgsql.neon tests/tests.local.neon; fi\""

script:
  - vendor/bin/tester tests -p php -s -c tests/php-unix.ini

notifications:
  email: false
