language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_script:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database testbench;'
  - composer selfupdate
  - travis_retry composer install --prefer-dist --dev
  - mkdir tests/_temp
  - "echo \"{'doctrine': {'user': 'travis', 'password': '', 'dbname': 'testbench'}}\" > tests/tests.local.neon"

script:
  - vendor/bin/tester tests -p php -s -c tests/php-unix.ini

notifications:
  email: false
