language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
  - vendor/bin/tester tests -p php -s -c tests/php.ini

before_script:
  - composer selfupdate
  - composer install --prefer-dist --no-dev

notifications:
  email: false